Fixed: Added Gum.csproj to the solution
isadorasophia/murder pull request #7
Opened 2023-09-14 13:25 UTC by TanukiCom

I added Gum.csproj back to the solution.
The editor will build and run like previous.

2023-09-15 05:23 UTC, isadorasophia requested changes
I'm mostly curious, how was the issue coming up? since *technically* Murder.Editor.csproj had a reference to the relative path of Gum

2023-09-15 05:23 UTC, isadorasophia commented on Murder.sln
>  		Debug|Any CPU = Debug|Any CPU
you need to add to the GlobalSection so it builds as part of the solution:
```
{4CBD9371-4090-49C0-82F7-CAB7DF68326E}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
{4CBD9371-4090-49C0-82F7-CAB7DF68326E}.Debug|Any CPU.Build.0 = Debug|Any CPU
{4CBD9371-4090-49C0-82F7-CAB7DF68326E}.Release|Any CPU.ActiveCfg = Release|Any CPU
{4CBD9371-4090-49C0-82F7-CAB7DF68326E}.Release|Any CPU.Build.0 = Release|Any CPU
```

(not sure why the "Add existing project..." gesture to the solution didn't pick that up)

2023-09-15 05:35 UTC, PadTrick commented
Had the same issue, there was an error during 1st opening the solution with vs_community_2022. Readding Gum to the Project solved it.
On Archlinux opening the solution with vs_code doesnt had this issue.

2023-09-17 08:55 UTC, isadorasophia commented
I ended up adding the Gum.csproj so it doesn't block anyone, thanks for the fix though! o/

2023-09-17 08:55 UTC, closed without merging